name: Pipeline de Integracion Continua

on:
  push:
    branches:
      - main

jobs:
  notificacion:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar entorno Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Ejecutar aplicacion
        run: node index.js

      - name: Enviar notificacion a ntfy
        run: |
          MENSAJE="Repositorio: ${{ github.repository }} | Commit: ${{ github.event.head_commit.message }} | Autor: ${{ github.actor }} | Enlace: https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
          
          curl -H "Title: Ejecucion exitosa de Integracion Continua" \
               -H "Priority: high" \
               -d "$MENSAJE" \
               https://ntfy.sh/devops-itla
